### ISSUE TITLE
MATLAB MEX AND MPI 

### ISSUE THREAD

**Issue by lacrymose** [sara-nl/matlabmpi#1]
Dear developers, I compiled the matlab mex file which involves mpi operations and when I re-run the mexfunction, it gave
*** The MPI_Init() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
I suspect the mpi is still working after MPI_FINALIZE is called in the first run, which causes the above error when MPI_Init() is called in the second run. But I donot know how to solve this problem. I ask a help from you. Thanks in advance!

**Comment by jjengelberts** [comment]
Hi lacrymose,

My name is Jeroen Engelberts. I initially wrote matlabmpi as part of [MMSODA](https://zenodo.org/record/1435005#.Y5rfXNLMJaQ) back in 2013. Between 2013 and 2018, the standalone version has been used by a couple of users on the Dutch National Supercomputer.

In 2018, I moved from SARA (later SURFsara, now SURF) to the Erasmus University and have not looked at the code since. However, I will have quite some hobby time around Christmas and will have a look at your question. If there is an issue, I can probably fix it. 

I do not know whether SURF is still maintaining the sara-nl Github group. I doubt whether I still have write access. Therefore, I forked the code to my own Github, which you can clone from here:

https://github.com/jjengelberts/matlabmpi

I will send them a pull request later, if I needed to fix the code.

I will build the example code and see if I can reproduce your error. In the mean time, could you tell me your version of 
* Operating system
* gcc
* MATLAB
* openmpi

Besides, are you able to run the example? Or are you stuck in your own derivation of my example?

Kind regards,

Jeroen Engelberts

**Comment by jjengelberts** [comment]
Hi lacrymose,

Just checking: did you call the "whoami()" function at the beginning of your MATLAB program? This will initialize MPI and return the MPI rank and size.

I tested my old code with:
* Linux Mint 21
* gcc 11.3.0
* MATLAB R2022b
* openmpi 4.1.2

And it ran without problems on 4 and 8 cores.

Kind regards,

Jeroen Engelberts

**Comment by niekbosch** [comment]
Closed on the request of Jeroen
